# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Starting the Pipeline!
  displayName: 'Start Build'


- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm-cache clean'
  displayName: 'clean npm cache'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'install npm'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm audit fix'
  displayName: 'fix npm audit'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm run build'
  displayName: 'run npm build'
