trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem -Path ''$(Build.SourcesDirectory)'''
  displayName: 'Get-ChildItem OF Build.SourcesDirectory'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem -Path ''$(System.DefaultWorkingDirectory)'''
  displayName: 'Get-ChildItem OF System.DefaultWorkingDirectory'
