trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: CmdLine@2
  inputs:
    script: 'echo $(Build.BinariesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'echo $(Build.Source)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: echo $(Build.Repository.LocalPath)
  displayName: 'Build.Repository.LocalPath'
  
- script: echo $(Build.SourceBranch)
  displayName: 'Build.SourceBranch'
  
- script: echo $(Build.StagingDirectory)
  displayName: 'Build.StagingDirectory'

- script: echo $(Build.ArtifactStagingDirectory)
  displayName: 'Build.ArtifactStagingDirectory' 

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

